services:
  - type: web
    name: pneumonia-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
  - type: static
    name: pneumonia-frontend
    staticPublishPath: .
    buildCommand: ''
    plan: free
    autoDeploy: true 